# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
 app.submit_json_listener:
  class: AppBundle\EventListener\SubmitJsonListener
  tags:
   - { name: kenerl.event_listener, event: kernel.request, method: onKernelRequest }
 app.forbidden_exception_listener:
  class: AppBundle\EventListener\ForbiddenExceptionListener
  tags:
   - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 10 }
